// AUTHENTICATION ACTIONS
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const REGISTER_REQUEST = "REGISTER_REQUEST";

// SINGLE MATCH ACTIONS
export const SINGLE_MATCH_LOADING = "SINGLE_MATCH_LOADING";
export const SINGLE_MATCH_SUCCESS = "SINGLE_MATCH_SUCCESS";
export const SINGLE_MATCH_FAILED = "SINGLE_MATCH_FAILED";

// ALL MATCHES ACTIONS
export const ALL_MATCHES_LOADING = "ALL_MATCHES_LOADING";
export const ALL_MATCHES_SUCCESS = "ALL_MATCHES_SUCCESS";
export const ALL_MATCHES_FAILED = "ALL_MATCHES_FAILED";